behaviors:
  SoccerTwos:
    trainer_type: poca
    hyperparameters:
      batch_size: 4096
      buffer_size: 40960
      learning_rate: 0.0003
      beta: 0.004
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 13
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 768
      num_layers: 5
      vis_encode_type: resnet
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 15000000
    time_horizon: 1000
    summary_freq: 10000
    self_play:
      save_steps: 50000
      team_change: 100000
      swap_steps: 2000
      window: 12
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0